services:
  classpage-db:
    image: postgres:16-alpine
    container_name: classpage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: classpage
      POSTGRES_PASSWORD: classpage1234
      POSTGRES_DB: classpage
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - classpage_pg_data:/var/lib/postgresql/data
      - ./database/init.postgresql.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  classpage_pg_data:
